### ISSUE TITLE
Reorganize the file structure in this repo

### ISSUE THREAD

**Issue by gluckzhang** [kth-tcs/chaos-ns-3#10]
Hi @Tailp , @zubayer123 ,
Now I will also publish kinds of tasks for you, hoping that will help you gain a better understanding of chaos engineering. Feel free to discuss if you have any questions, we can also book a meeting with Martin in the future to synchronize up :)
This issue is about our repo's file structure, only storing the basic scrips is not enough, my suggestion is:

```
|-README.md (Basic introduction, like how to run the scripts, relevant website or kinds of useful links)
|-first (Directory, all the staff about your experiments on this script)
|--|--first.cc (The first original script, it's better to add some code comments if you need)
|--|--first.cc.log (The output of this original script, so that we will know what's the correct output of this script)
|--|--first_chaos.cc (If it's hard for you to do the chaos automatically, you can make some assumptions and manually inject some faults in the script, to see how the network react to the perturbation. It good to analyze the script deeply, and find out different injection points by yourself. It's useful for you to implement the chaos controller later.)
|--|--first_chaos.cc.log (The output under fault injection, maybe you will commit more than one log file if you have many fault injection points)
|--|--SUMMERY.md (A short summery about this script, you can introduce what network this script is trying to simulate, what injections you have done and why the network reacted like that)
|-second (Directory, all the staff about your experiments on this script)
|--|--... same with first one
|-third (Directory, all the staff about your experiments on this script)
...
|-case_Netflix (We are aiming at doing some simulations on Netflix's network / microservice structure, so after you have gained enough knowledge, you should design a script to simulate Netflix's network, and do some chaos engineering things on that)
|-controller (This directory will be used to store chaos controller scripts, you should be able to do chaos automatically, a so-called chaos controller will be implemented in the future)
```

**Comment by Tailp** [comment]
Hi Long ! 
Chaos controller . Can you specify a little more what it does :) . Is it some kinda script where you have all your chaos injection types or is it something else ? .

**Comment by gluckzhang** [comment]
Hi @Tailp , regarding the chaos controller, it's mainly responsible for controlling the perturbation process and analyzing the information generated during the experiments, automatically. That is to say you just need to run this controller in the beginning, then it will help you record everything you need and switch injection operations during the run-time.
Another aspect is that imagine that if you could design the chaos tool in a common way, easily changing the injection positions and failure types with some configure files, that will be better for others to reuse your tool. For example, you are now designing the chaos engineering modules on Netflix's network model on NS-3, later I want to do some similar experiments on other network model, can your tool be reused for me? If you mixed your chaos codes into the original model, that will be impossible for me to take advantage of.
That's why we may need to implement this controller separately. But I guess you can do the chaos case by case for the current phase, when you are more familiar with how to perturb on the models, you can implement the controller then.

**Comment by Tailp** [comment]
Thank you Long :) . Ok so you want something to analyze the output of the system and take action according to that . Like if it see a node then it will look it up and destroy it . I ll put it as our first priority .

**Comment by Tailp** [comment]
Hi Long ! I have finished the skeletion of my automatic fault injection . There are some more injection point which I should include later on . Now It is quite late so I ll leave it till tomorrow when I have time , but the concept is the same for second.cc and third.cc or any other ns3 program. 
![screenshot from 2018-03-30 00-52-46](https://user-images.githubusercontent.com/33935517/38117450-4c1dc3c8-33b5-11e8-871a-57b64f8a7b6e.png)

I have include the file which run this and give out the screenshot I show you above . So if the experiment is success then it will continue on and inject fault further into the component or move on into another component . Like ( inject Datarate -> Ok Its fine -> inject fault by destroying the NetDevice -> Ok nice it fixed it -> Destroy a node -> Ok we got a SIGSEGV , the developer then troubleshoot the problem and include his own self-healing system like the case I showed with the datarate experiment and then rerun the experiment and check if it is solved ) . In this program you can run one or many fault injection , just by modify a bit of your code . You can also add more monkey by making more MyMonkey object to disturb at different time instances and see if your ns3 program can handle it (I ll need to adjust a bit tomorrow so it will work more smoothly) . The point is that you can now decide and build your chaos paths in the controller so the program can react on the output parameter whether if it is a success or failure and take action according to it . It might be vague but I am quite tired so If there are some problems , I ll solve it tomorrow :) . Ah and the first version of this is in the <>Code in my github . I am still not very used to this github thing. I ll put the files here so Martin can also check it .
Best
Tai

**Comment by Tailp** [comment]
I forgot to tell how I ran the program. You put the three files first_chaos.cc, firstcontroller.cc and firstlogsnonchaos.txt in ns-3-dev/Scratch folder Then in the Ubuntu terminal ./waf --run Scratch/firstcontroller , if you are in the ns-3-dev folder . You should then get the result I've shown in the screenshot .

**Comment by Tailp** [comment]
How does the NetFlix module work:
The Idea is that we have a main netflix node where all the clients(StaNodes) can connect to this node through their own router modem(ApNodes) . The situation can be like when a client request a movie streaming of NetFlix . This request forwards then to the instances(Csmanodes) which are responsible for this request. When the requested information is ready it then sends back to the client(StaNodes).

**Comment by Tailp** [comment]
Hi Long ! 
I forgot to comment out some stuffs in my caseNetFlix files when I upploaded so I dont think It worked back then :) . I just changed a bit in caseNetFlix files so It should work as long as you have replaced all the header files . Sorry for the trouble.

**Comment by Tailp** [comment]
![screenshot from 2018-04-17 18-53-45](https://user-images.githubusercontent.com/33935517/38884712-b34d68e0-4270-11e8-89db-d3071c676f2a.png)

Hi Long!
I am finished with the one case of the LDFI . In this case I only use p2pnodes in order to demonstrate the idea where I am able to spot the weakness of the system according to LDFI reasoning . I will be explaining the main idea of the programs here and leave all the gory details about how to calculate chaos hypothesis and map roads and such when we meet next week . 

The main idea is that in this second version of NetFlix module I have make it possible so that you can map all possible roads from a service node to another service node . The controller will then run the module (NetFlix ver2) in its nonchaos state in order to obtain these [PlanedSendEvent] . This [PlanedSendEvent] tells us from which service does this signal start and to which service does this signal ends , well in this case is the sending event where the client node is planing to send a package to a server . The controller catch these kinds of info and use them to request the netflixmodule to give back all possible roads to produce the same kind of ending (in our case you can see in the picture the possible roads is 0,1,4|0,2,4|0,3,4| ) . The controller will then use these infos to calculate all of the hypothesis in order to fail these events , which I call chaos paths . The controller use these chaos paths to inject fault in the program to fail these node so that the signal is expected to not be able to arrive to is destination . The experiment will then be deemed as success .

**Comment by Tailp** [comment]
![screenshot from 2018-04-17 19-06-34](https://user-images.githubusercontent.com/33935517/38885205-7681d368-4272-11e8-862e-aa0c5027acef.png)
Here you can see that the controller have successfully acquired all of the possible roads and calculated the chaos solution(chaos path) . It then commences the LDFI with these solutions and got outcomes where the signal did not echo back . This echo is an equivalence or maybe a simplification of the message which tells whether the signal have reached its destination or not in Deadalus.

**Comment by Tailp** [comment]
Ok here comes caseNetFlixver2dot1 . 
![screenshot from 2018-04-17 20-22-58](https://user-images.githubusercontent.com/33935517/38888918-562ebd1e-427d-11e8-8da8-012c790985c8.png)

![screenshot from 2018-04-17 20-25-30](https://user-images.githubusercontent.com/33935517/38888972-7ec94b7c-427d-11e8-99ee-bbaa03ba7c01.png)

**Comment by Tailp** [comment]
and finally caseNetFlixchaosver2dot2
![screenshot from 2018-04-17 21-07-20](https://user-images.githubusercontent.com/33935517/38891058-795b3ba4-4283-11e8-9b1b-d47dd649e927.png)
![screenshot from 2018-04-17 21-06-31](https://user-images.githubusercontent.com/33935517/38891059-7adca5bc-4283-11e8-9044-0559f9872d2f.png)

**Comment by Tailp** [comment]
Hi Long ! 
I fixed the roads output so that it output correctly . Maybe you noticed in my caseNetFlixver2dot2 it output several 0,1,2,3,4,5 roads . This is because when I am calculating the chaos path I used the ordered set so the permutated roads like 0,1,4,2,3,5 and such will all become 0,1,2,3,4,5 . Yes I just fixed that one so It doesnt look weird anymore . 
I know that you and Martin have much to do so this week . You can check this and we'll discuss more next week . :) 
Best

![screenshot from 2018-04-18 13-03-47](https://user-images.githubusercontent.com/33935517/38928554-7d9f44d6-4309-11e8-95eb-28185cc02eb4.png)

**Comment by gluckzhang** [comment]
Hi @Tailp ,
Thanks for updating the progress regularly! I am still writing the paper and haven't got time to read carefully yet. But it's obvious to see that you and Anton are doing great. Don't forget to summarize these outputs in your paper, maybe we can discuss more next week :)

**Comment by Tailp** [comment]
I fully understand Long :) . Me and Anton are very safe with our bachelor thesis now , so dont worry about us :) . Yes I would like to discuss with you next week . As it said in the progress I am doing some cleaning right now in our messy commits.  . I wish you success on your and Martins paper :) .

**Comment by Tailp** [comment]
CaseNetFlix version 4

![originalver4](https://user-images.githubusercontent.com/33935517/39961452-9f28d17c-5636-11e8-801b-c8dbd900a7b1.png)

LDFI for version 4
![casenetflixver4ldfioutput](https://user-images.githubusercontent.com/33935517/39961455-ac1dcd56-5636-11e8-94f9-c0e652859da3.png)
