### ISSUE TITLE
some useful information about computer networking and ns-3

### ISSUE THREAD

**Issue by gluckzhang** [kth-tcs/chaos-ns-3#7]
# computer networking
*Read more materials about computer networking will help you understand better about why your experiments should be done like that.*

[Computer Networking Tutorials On Youtube](https://www.youtube.com/watch?v=ueVnSz_lXEs&list=PL6gx4Cwl9DGBpuvPW0aHa7mKdn_k9SPKO)
[Computer Networking : Principles, Protocols and Practice](http://cnp3book.info.ucl.ac.be/2nd/cnp3bis.pdf)

# ns3

[ns-3 documentation](https://www.nsnam.org/doxygen/index.html)
[ns-3 Google Forum](https://groups.google.com/forum/#!forum/ns-3-users)
[ns-3 Tutorials On Youtube](https://www.youtube.com/watch?v=1FBSAghbjNM&list=PLmcMMZCV897qkb1fv177Y69hX8YhcmVpS)

**Comment by Tailp** [comment]
Other materials
[1702.05843.pdf](https://github.com/kth-tcs/chaos-ns-3/files/1745864/1702.05843.pdf)
[chaos-engineering book.pdf](https://github.com/kth-tcs/chaos-ns-3/files/1745865/chaos-engineering.book.pdf)
[cnp3bis.pdf](https://github.com/kth-tcs/chaos-ns-3/files/1745866/cnp3bis.pdf)
[ns-3-tutorial.pdf](https://github.com/kth-tcs/chaos-ns-3/files/1745867/ns-3-tutorial.pdf)
[socc16.pdf](https://github.com/kth-tcs/chaos-ns-3/files/1745868/socc16.pdf)
[TCP_IP_Sockets_in_C__Practical_Guide_for_Programmers.pdf](https://github.com/kth-tcs/chaos-ns-3/files/1745869/TCP_IP_Sockets_in_C__Practical_Guide_for_Programmers.pdf) /first 4 chapters

**Comment by Tailp** [comment]
http://www.cplusplus.com/doc/tutorial/program_structure

**Comment by Tailp** [comment]
http://www.cplusplus.com/forum/articles/12974/ 
Exercises for c++

**Comment by Tailp** [comment]
https://www.hermetic.ch/cfunlib/ast_amp2.htm

**Comment by Tailp** [comment]
http://www.cs.cmu.edu/~gilpin/tutorial/

**Comment by Tailp** [comment]
https://www.nsnam.org/docs/manual/html/logging.html

**Comment by Tailp** [comment]
https://www.researchgate.net/publication/271419947_A_Wi-Fi_Simulation_Model_Which_Supports_Channel_Scanning_across_Multiple_Non-overlapping_Channels_in_NS3

**Comment by zubayer123** [comment]
https://github.com/dastergon/awesome-chaos-engineering
